CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,

  version INT NOT NULL,

  creation_time TIMESTAMP NOT NULL,
  modification_time TIMESTAMP NOT NULL,
  deletion_time TIMESTAMP,

  username VARCHAR(255) NOT NULL UNIQUE
);
